### ISSUE TITLE
Changer la langue de la page.

### ISSUE THREAD

**Issue by PGaillot** [HugoBDev/AQD-WelcomePage#3]
quand on ouvre le site (en particulier sur mobile)
mon navigateur me propose de traduire la page en Français alors que celle ci l'est déjà.

changer la langue par défaut en Français dans `index.html`

![Capture d'écran 2024-03-14 114356](https://github.com/HugoBDev/AQD-WelcomePage/assets/93736766/976a6678-3c04-4e44-8c52-b56fe1d935f0)

**Comment by HugoBDev** [comment]
fixed ✅
